---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tatisanchez24
spec:
  memberOf: [backstage-admins, infinity]
  profile:
    displayName: Tatiana Sanchez
    email: tatianasanchez@seti.com.co
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage-admins
spec:
  type: team
  children: [infinity]

---

# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infinity
  description: "Infinity is the team that manages the Backstage instance."
spec:
  type: team
  profile:
    displayName: Infinity Team
    email: infinity@seti.com.co
  children: []
